namespace ApplicationNET6PreviewSandbox.Models
{
    public static class CountryInitalizer
    {
        public static void Initialize(CountryDbContext db)
        {
            if (db.Countries.Any())
            {
                return;
            }

            var countries = new List<Country>
            {
                new Country { Code = "ABW", Name = "Aruba", Continent = "North America", Region = "Caribbean", Population = 103000},
                new Country { Code = "AFG", Name = "Afghanistan", Continent = "Asia", Region = "Southern and Central Asia", Population = 22720000},
                new Country { Code = "AGO", Name = "Angola", Continent = "Africa", Region = "Central Africa", Population = 12878000},
                new Country { Code = "AIA", Name = "Anguilla", Continent = "North America", Region = "Caribbean", Population = 8000},
                new Country { Code = "ALB", Name = "Albania", Continent = "Europe", Region = "Southern Europe", Population = 3401200},
                new Country { Code = "AND", Name = "Andorra", Continent = "Europe", Region = "Southern Europe", Population = 78000},
                new Country { Code = "ANT", Name = "Netherlands Antilles", Continent = "North America", Region = "Caribbean", Population = 217000},
                new Country { Code = "ARE", Name = "United Arab Emirates", Continent = "Asia", Region = "Middle East", Population = 2441000},
                new Country { Code = "ARG", Name = "Argentina", Continent = "South America", Region = "South America", Population = 37032000},
                new Country { Code = "ARM", Name = "Armenia", Continent = "Asia", Region = "Middle East", Population = 3520000},
                new Country { Code = "ASM", Name = "American Samoa", Continent = "Oceania", Region = "Polynesia", Population = 68000},
                new Country { Code = "ATA", Name = "Antarctica", Continent = "Antarctica", Region = "Antarctica", Population = 0},
                new Country { Code = "ATF", Name = "French Southern territories", Continent = "Antarctica", Region = "Antarctica", Population = 0},
                new Country { Code = "ATG", Name = "Antigua and Barbuda", Continent = "North America", Region = "Caribbean", Population = 68000},
                new Country { Code = "AUS", Name = "Australia", Continent = "Oceania", Region = "Australia and New Zealand", Population = 18886000},
                new Country { Code = "AUT", Name = "Austria", Continent = "Europe", Region = "Western Europe", Population = 8091800},
                new Country { Code = "AZE", Name = "Azerbaijan", Continent = "Asia", Region = "Middle East", Population = 7734000},
                new Country { Code = "BDI", Name = "Burundi", Continent = "Africa", Region = "Eastern Africa", Population = 6695000},
                new Country { Code = "BEL", Name = "Belgium", Continent = "Europe", Region = "Western Europe", Population = 10239000},
                new Country { Code = "BEN", Name = "Benin", Continent = "Africa", Region = "Western Africa", Population = 6097000},
                new Country { Code = "BFA", Name = "Burkina Faso", Continent = "Africa", Region = "Western Africa", Population = 11937000},
                new Country { Code = "BGD", Name = "Bangladesh", Continent = "Asia", Region = "Southern and Central Asia", Population = 129155000},
                new Country { Code = "BGR", Name = "Bulgaria", Continent = "Europe", Region = "Eastern Europe", Population = 8190900},
                new Country { Code = "BHR", Name = "Bahrain", Continent = "Asia", Region = "Middle East", Population = 617000},
                new Country { Code = "BHS", Name = "Bahamas", Continent = "North America", Region = "Caribbean", Population = 307000},
                new Country { Code = "BIH", Name = "Bosnia and Herzegovina", Continent = "Europe", Region = "Southern Europe", Population = 3972000},
                new Country { Code = "BLR", Name = "Belarus", Continent = "Europe", Region = "Eastern Europe", Population = 10236000},
                new Country { Code = "BLZ", Name = "Belize", Continent = "North America", Region = "Central America", Population = 241000},
                new Country { Code = "BMU", Name = "Bermuda", Continent = "North America", Region = "North America", Population = 65000},
                new Country { Code = "BOL", Name = "Bolivia", Continent = "South America", Region = "South America", Population = 8329000},
                new Country { Code = "BRA", Name = "Brazil", Continent = "South America", Region = "South America", Population = 170115000},
                new Country { Code = "BRB", Name = "Barbados", Continent = "North America", Region = "Caribbean", Population = 280000},
                new Country { Code = "BRN", Name = "Brunei", Continent = "Asia", Region = "Southeast Asia", Population = 328000},
                new Country { Code = "BTN", Name = "Bhutan", Continent = "Asia", Region = "Southern and Central Asia", Population = 2124000},
                new Country { Code = "BVT", Name = "Bouvet Island", Continent = "Antarctica", Region = "Antarctica", Population = 0},
                new Country { Code = "BWA", Name = "Botswana", Continent = "Africa", Region = "Southern Africa", Population = 1622000},
                new Country { Code = "CAF", Name = "Central African Republic", Continent = "Africa", Region = "Central Africa", Population = 3615000},
                new Country { Code = "CAN", Name = "Canada", Continent = "North America", Region = "North America", Population = 31147000},
                new Country { Code = "CCK", Name = "Cocos (Keeling) Islands", Continent = "Oceania", Region = "Australia and New Zealand", Population = 600},
                new Country { Code = "CHE", Name = "Switzerland", Continent = "Europe", Region = "Western Europe", Population = 7160400},
                new Country { Code = "CHL", Name = "Chile", Continent = "South America", Region = "South America", Population = 15211000},
                new Country { Code = "CHN", Name = "China", Continent = "Asia", Region = "Eastern Asia", Population = 1277558000},
                new Country { Code = "CIV", Name = "CÃ´te dÂ’Ivoire", Continent = "Africa", Region = "Western Africa", Population = 14786000},
                new Country { Code = "CMR", Name = "Cameroon", Continent = "Africa", Region = "Central Africa", Population = 15085000},
                new Country { Code = "COD", Name = "Congo, The Democratic Republic of the", Continent = "Africa", Region = "Central Africa", Population = 51654000},
                new Country { Code = "COG", Name = "Congo", Continent = "Africa", Region = "Central Africa", Population = 2943000},
                new Country { Code = "COK", Name = "Cook Islands", Continent = "Oceania", Region = "Polynesia", Population = 20000},
                new Country { Code = "COL", Name = "Colombia", Continent = "South America", Region = "South America", Population = 42321000},
                new Country { Code = "COM", Name = "Comoros", Continent = "Africa", Region = "Eastern Africa", Population = 578000},
                new Country { Code = "CPV", Name = "Cape Verde", Continent = "Africa", Region = "Western Africa", Population = 428000},
                new Country { Code = "CRI", Name = "Costa Rica", Continent = "North America", Region = "Central America", Population = 4023000},
                new Country { Code = "CUB", Name = "Cuba", Continent = "North America", Region = "Caribbean", Population = 11201000},
                new Country { Code = "CXR", Name = "Christmas Island", Continent = "Oceania", Region = "Australia and New Zealand", Population = 2500},
                new Country { Code = "CYM", Name = "Cayman Islands", Continent = "North America", Region = "Caribbean", Population = 38000},
                new Country { Code = "CYP", Name = "Cyprus", Continent = "Asia", Region = "Middle East", Population = 754700},
                new Country { Code = "CZE", Name = "Czech Republic", Continent = "Europe", Region = "Eastern Europe", Population = 10278100},
                new Country { Code = "DEU", Name = "Germany", Continent = "Europe", Region = "Western Europe", Population = 82164700},
                new Country { Code = "DJI", Name = "Djibouti", Continent = "Africa", Region = "Eastern Africa", Population = 638000},
                new Country { Code = "DMA", Name = "Dominica", Continent = "North America", Region = "Caribbean", Population = 71000},
                new Country { Code = "DNK", Name = "Denmark", Continent = "Europe", Region = "Nordic Countries", Population = 5330000},
                new Country { Code = "DOM", Name = "Dominican Republic", Continent = "North America", Region = "Caribbean", Population = 8495000},
                new Country { Code = "DZA", Name = "Algeria", Continent = "Africa", Region = "Northern Africa", Population = 31471000},
                new Country { Code = "ECU", Name = "Ecuador", Continent = "South America", Region = "South America", Population = 12646000},
                new Country { Code = "EGY", Name = "Egypt", Continent = "Africa", Region = "Northern Africa", Population = 68470000},
                new Country { Code = "ERI", Name = "Eritrea", Continent = "Africa", Region = "Eastern Africa", Population = 3850000},
                new Country { Code = "ESH", Name = "Western Sahara", Continent = "Africa", Region = "Northern Africa", Population = 293000},
                new Country { Code = "ESP", Name = "Spain", Continent = "Europe", Region = "Southern Europe", Population = 39441700},
                new Country { Code = "EST", Name = "Estonia", Continent = "Europe", Region = "Baltic Countries", Population = 1439200},
                new Country { Code = "ETH", Name = "Ethiopia", Continent = "Africa", Region = "Eastern Africa", Population = 62565000},
                new Country { Code = "FIN", Name = "Finland", Continent = "Europe", Region = "Nordic Countries", Population = 5171300},
                new Country { Code = "FJI", Name = "Fiji Islands", Continent = "Oceania", Region = "Melanesia", Population = 817000},
                new Country { Code = "FLK", Name = "Falkland Islands", Continent = "South America", Region = "South America", Population = 2000},
                new Country { Code = "FRA", Name = "France", Continent = "Europe", Region = "Western Europe", Population = 59225700},
                new Country { Code = "FRO", Name = "Faroe Islands", Continent = "Europe", Region = "Nordic Countries", Population = 43000},
                new Country { Code = "FSM", Name = "Micronesia, Federated States of", Continent = "Oceania", Region = "Micronesia", Population = 119000},
                new Country { Code = "GAB", Name = "Gabon", Continent = "Africa", Region = "Central Africa", Population = 1226000},
                new Country { Code = "GBR", Name = "United Kingdom", Continent = "Europe", Region = "British Islands", Population = 59623400},
                new Country { Code = "GEO", Name = "Georgia", Continent = "Asia", Region = "Middle East", Population = 4968000},
                new Country { Code = "GHA", Name = "Ghana", Continent = "Africa", Region = "Western Africa", Population = 20212000},
                new Country { Code = "GIB", Name = "Gibraltar", Continent = "Europe", Region = "Southern Europe", Population = 25000},
                new Country { Code = "GIN", Name = "Guinea", Continent = "Africa", Region = "Western Africa", Population = 7430000},
                new Country { Code = "GLP", Name = "Guadeloupe", Continent = "North America", Region = "Caribbean", Population = 456000},
                new Country { Code = "GMB", Name = "Gambia", Continent = "Africa", Region = "Western Africa", Population = 1305000},
                new Country { Code = "GNB", Name = "Guinea-Bissau", Continent = "Africa", Region = "Western Africa", Population = 1213000},
                new Country { Code = "GNQ", Name = "Equatorial Guinea", Continent = "Africa", Region = "Central Africa", Population = 453000},
                new Country { Code = "GRC", Name = "Greece", Continent = "Europe", Region = "Southern Europe", Population = 10545700},
                new Country { Code = "GRD", Name = "Grenada", Continent = "North America", Region = "Caribbean", Population = 94000},
                new Country { Code = "GRL", Name = "Greenland", Continent = "North America", Region = "North America", Population = 56000},
                new Country { Code = "GTM", Name = "Guatemala", Continent = "North America", Region = "Central America", Population = 11385000},
                new Country { Code = "GUF", Name = "French Guiana", Continent = "South America", Region = "South America", Population = 181000},
                new Country { Code = "GUM", Name = "Guam", Continent = "Oceania", Region = "Micronesia", Population = 168000},
                new Country { Code = "GUY", Name = "Guyana", Continent = "South America", Region = "South America", Population = 861000},
                new Country { Code = "HKG", Name = "Hong Kong", Continent = "Asia", Region = "Eastern Asia", Population = 6782000},
                new Country { Code = "HMD", Name = "Heard Island and McDonald Islands", Continent = "Antarctica", Region = "Antarctica", Population = 0},
                new Country { Code = "HND", Name = "Honduras", Continent = "North America", Region = "Central America", Population = 6485000},
                new Country { Code = "HRV", Name = "Croatia", Continent = "Europe", Region = "Southern Europe", Population = 4473000},
                new Country { Code = "HTI", Name = "Haiti", Continent = "North America", Region = "Caribbean", Population = 8222000},
                new Country { Code = "HUN", Name = "Hungary", Continent = "Europe", Region = "Eastern Europe", Population = 10043200},
                new Country { Code = "IDN", Name = "Indonesia", Continent = "Asia", Region = "Southeast Asia", Population = 212107000},
                new Country { Code = "IND", Name = "India", Continent = "Asia", Region = "Southern and Central Asia", Population = 1013662000},
                new Country { Code = "IOT", Name = "British Indian Ocean Territory", Continent = "Africa", Region = "Eastern Africa", Population = 0},
                new Country { Code = "IRL", Name = "Ireland", Continent = "Europe", Region = "British Islands", Population = 3775100},
                new Country { Code = "IRN", Name = "Iran", Continent = "Asia", Region = "Southern and Central Asia", Population = 67702000},
                new Country { Code = "IRQ", Name = "Iraq", Continent = "Asia", Region = "Middle East", Population = 23115000},
                new Country { Code = "ISL", Name = "Iceland", Continent = "Europe", Region = "Nordic Countries", Population = 279000},
                new Country { Code = "ISR", Name = "Israel", Continent = "Asia", Region = "Middle East", Population = 6217000},
                new Country { Code = "ITA", Name = "Italy", Continent = "Europe", Region = "Southern Europe", Population = 57680000},
                new Country { Code = "JAM", Name = "Jamaica", Continent = "North America", Region = "Caribbean", Population = 2583000},
                new Country { Code = "JOR", Name = "Jordan", Continent = "Asia", Region = "Middle East", Population = 5083000},
                new Country { Code = "JPN", Name = "Japan", Continent = "Asia", Region = "Eastern Asia", Population = 126714000},
                new Country { Code = "KAZ", Name = "Kazakstan", Continent = "Asia", Region = "Southern and Central Asia", Population = 16223000},
                new Country { Code = "KEN", Name = "Kenya", Continent = "Africa", Region = "Eastern Africa", Population = 30080000},
                new Country { Code = "KGZ", Name = "Kyrgyzstan", Continent = "Asia", Region = "Southern and Central Asia", Population = 4699000},
                new Country { Code = "KHM", Name = "Cambodia", Continent = "Asia", Region = "Southeast Asia", Population = 11168000},
                new Country { Code = "KIR", Name = "Kiribati", Continent = "Oceania", Region = "Micronesia", Population = 83000},
                new Country { Code = "KNA", Name = "Saint Kitts and Nevis", Continent = "North America", Region = "Caribbean", Population = 38000},
                new Country { Code = "KOR", Name = "South Korea", Continent = "Asia", Region = "Eastern Asia", Population = 46844000},
                new Country { Code = "KWT", Name = "Kuwait", Continent = "Asia", Region = "Middle East", Population = 1972000},
                new Country { Code = "LAO", Name = "Laos", Continent = "Asia", Region = "Southeast Asia", Population = 5433000},
                new Country { Code = "LBN", Name = "Lebanon", Continent = "Asia", Region = "Middle East", Population = 3282000},
                new Country { Code = "LBR", Name = "Liberia", Continent = "Africa", Region = "Western Africa", Population = 3154000},
                new Country { Code = "LBY", Name = "Libyan Arab Jamahiriya", Continent = "Africa", Region = "Northern Africa", Population = 5605000},
                new Country { Code = "LCA", Name = "Saint Lucia", Continent = "North America", Region = "Caribbean", Population = 154000},
                new Country { Code = "LIE", Name = "Liechtenstein", Continent = "Europe", Region = "Western Europe", Population = 32300},
                new Country { Code = "LKA", Name = "Sri Lanka", Continent = "Asia", Region = "Southern and Central Asia", Population = 18827000},
                new Country { Code = "LSO", Name = "Lesotho", Continent = "Africa", Region = "Southern Africa", Population = 2153000},
                new Country { Code = "LTU", Name = "Lithuania", Continent = "Europe", Region = "Baltic Countries", Population = 3698500},
                new Country { Code = "LUX", Name = "Luxembourg", Continent = "Europe", Region = "Western Europe", Population = 435700},
                new Country { Code = "LVA", Name = "Latvia", Continent = "Europe", Region = "Baltic Countries", Population = 2424200},
                new Country { Code = "MAC", Name = "Macao", Continent = "Asia", Region = "Eastern Asia", Population = 473000},
                new Country { Code = "MAR", Name = "Morocco", Continent = "Africa", Region = "Northern Africa", Population = 28351000},
                new Country { Code = "MCO", Name = "Monaco", Continent = "Europe", Region = "Western Europe", Population = 34000},
                new Country { Code = "MDA", Name = "Moldova", Continent = "Europe", Region = "Eastern Europe", Population = 4380000},
                new Country { Code = "MDG", Name = "Madagascar", Continent = "Africa", Region = "Eastern Africa", Population = 15942000},
                new Country { Code = "MDV", Name = "Maldives", Continent = "Asia", Region = "Southern and Central Asia", Population = 286000},
                new Country { Code = "MEX", Name = "Mexico", Continent = "North America", Region = "Central America", Population = 98881000},
                new Country { Code = "MHL", Name = "Marshall Islands", Continent = "Oceania", Region = "Micronesia", Population = 64000},
                new Country { Code = "MKD", Name = "Macedonia", Continent = "Europe", Region = "Southern Europe", Population = 2024000},
                new Country { Code = "MLI", Name = "Mali", Continent = "Africa", Region = "Western Africa", Population = 11234000},
                new Country { Code = "MLT", Name = "Malta", Continent = "Europe", Region = "Southern Europe", Population = 380200},
                new Country { Code = "MMR", Name = "Myanmar", Continent = "Asia", Region = "Southeast Asia", Population = 45611000},
                new Country { Code = "MNG", Name = "Mongolia", Continent = "Asia", Region = "Eastern Asia", Population = 2662000},
                new Country { Code = "MNP", Name = "Northern Mariana Islands", Continent = "Oceania", Region = "Micronesia", Population = 78000},
                new Country { Code = "MOZ", Name = "Mozambique", Continent = "Africa", Region = "Eastern Africa", Population = 19680000},
                new Country { Code = "MRT", Name = "Mauritania", Continent = "Africa", Region = "Western Africa", Population = 2670000},
                new Country { Code = "MSR", Name = "Montserrat", Continent = "North America", Region = "Caribbean", Population = 11000},
                new Country { Code = "MTQ", Name = "Martinique", Continent = "North America", Region = "Caribbean", Population = 395000},
                new Country { Code = "MUS", Name = "Mauritius", Continent = "Africa", Region = "Eastern Africa", Population = 1158000},
                new Country { Code = "MWI", Name = "Malawi", Continent = "Africa", Region = "Eastern Africa", Population = 10925000},
                new Country { Code = "MYS", Name = "Malaysia", Continent = "Asia", Region = "Southeast Asia", Population = 22244000},
                new Country { Code = "MYT", Name = "Mayotte", Continent = "Africa", Region = "Eastern Africa", Population = 149000},
                new Country { Code = "NAM", Name = "Namibia", Continent = "Africa", Region = "Southern Africa", Population = 1726000},
                new Country { Code = "NCL", Name = "New Caledonia", Continent = "Oceania", Region = "Melanesia", Population = 214000},
                new Country { Code = "NER", Name = "Niger", Continent = "Africa", Region = "Western Africa", Population = 10730000},
                new Country { Code = "NFK", Name = "Norfolk Island", Continent = "Oceania", Region = "Australia and New Zealand", Population = 2000},
                new Country { Code = "NGA", Name = "Nigeria", Continent = "Africa", Region = "Western Africa", Population = 111506000},
                new Country { Code = "NIC", Name = "Nicaragua", Continent = "North America", Region = "Central America", Population = 5074000},
                new Country { Code = "NIU", Name = "Niue", Continent = "Oceania", Region = "Polynesia", Population = 2000},
                new Country { Code = "NLD", Name = "Netherlands", Continent = "Europe", Region = "Western Europe", Population = 15864000},
                new Country { Code = "NOR", Name = "Norway", Continent = "Europe", Region = "Nordic Countries", Population = 4478500},
                new Country { Code = "NPL", Name = "Nepal", Continent = "Asia", Region = "Southern and Central Asia", Population = 23930000},
                new Country { Code = "NRU", Name = "Nauru", Continent = "Oceania", Region = "Micronesia", Population = 12000},
                new Country { Code = "NZL", Name = "New Zealand", Continent = "Oceania", Region = "Australia and New Zealand", Population = 3862000},
                new Country { Code = "OMN", Name = "Oman", Continent = "Asia", Region = "Middle East", Population = 2542000},
                new Country { Code = "PAK", Name = "Pakistan", Continent = "Asia", Region = "Southern and Central Asia", Population = 156483000},
                new Country { Code = "PAN", Name = "Panama", Continent = "North America", Region = "Central America", Population = 2856000},
                new Country { Code = "PCN", Name = "Pitcairn", Continent = "Oceania", Region = "Polynesia", Population = 50},
                new Country { Code = "PER", Name = "Peru", Continent = "South America", Region = "South America", Population = 25662000},
                new Country { Code = "PHL", Name = "Philippines", Continent = "Asia", Region = "Southeast Asia", Population = 75967000},
                new Country { Code = "PLW", Name = "Palau", Continent = "Oceania", Region = "Micronesia", Population = 19000},
                new Country { Code = "PNG", Name = "Papua New Guinea", Continent = "Oceania", Region = "Melanesia", Population = 4807000},
                new Country { Code = "POL", Name = "Poland", Continent = "Europe", Region = "Eastern Europe", Population = 38653600},
                new Country { Code = "PRI", Name = "Puerto Rico", Continent = "North America", Region = "Caribbean", Population = 3869000},
                new Country { Code = "PRK", Name = "North Korea", Continent = "Asia", Region = "Eastern Asia", Population = 24039000},
                new Country { Code = "PRT", Name = "Portugal", Continent = "Europe", Region = "Southern Europe", Population = 9997600},
                new Country { Code = "PRY", Name = "Paraguay", Continent = "South America", Region = "South America", Population = 5496000},
                new Country { Code = "PSE", Name = "Palestine", Continent = "Asia", Region = "Middle East", Population = 3101000},
                new Country { Code = "PYF", Name = "French Polynesia", Continent = "Oceania", Region = "Polynesia", Population = 235000},
                new Country { Code = "QAT", Name = "Qatar", Continent = "Asia", Region = "Middle East", Population = 599000},
                new Country { Code = "REU", Name = "RÃ©union", Continent = "Africa", Region = "Eastern Africa", Population = 699000},
                new Country { Code = "ROM", Name = "Romania", Continent = "Europe", Region = "Eastern Europe", Population = 22455500},
                new Country { Code = "RUS", Name = "Russian Federation", Continent = "Europe", Region = "Eastern Europe", Population = 146934000},
                new Country { Code = "RWA", Name = "Rwanda", Continent = "Africa", Region = "Eastern Africa", Population = 7733000},
                new Country { Code = "SAU", Name = "Saudi Arabia", Continent = "Asia", Region = "Middle East", Population = 21607000},
                new Country { Code = "SDN", Name = "Sudan", Continent = "Africa", Region = "Northern Africa", Population = 29490000},
                new Country { Code = "SEN", Name = "Senegal", Continent = "Africa", Region = "Western Africa", Population = 9481000},
                new Country { Code = "SGP", Name = "Singapore", Continent = "Asia", Region = "Southeast Asia", Population = 3567000},
                new Country { Code = "SGS", Name = "South Georgia and the South Sandwich Islands", Continent = "Antarctica", Region = "Antarctica", Population = 0},
                new Country { Code = "SHN", Name = "Saint Helena", Continent = "Africa", Region = "Western Africa", Population = 6000},
                new Country { Code = "SJM", Name = "Svalbard and Jan Mayen", Continent = "Europe", Region = "Nordic Countries", Population = 3200},
                new Country { Code = "SLB", Name = "Solomon Islands", Continent = "Oceania", Region = "Melanesia", Population = 444000},
                new Country { Code = "SLE", Name = "Sierra Leone", Continent = "Africa", Region = "Western Africa", Population = 4854000},
                new Country { Code = "SLV", Name = "El Salvador", Continent = "North America", Region = "Central America", Population = 6276000},
                new Country { Code = "SMR", Name = "San Marino", Continent = "Europe", Region = "Southern Europe", Population = 27000},
                new Country { Code = "SOM", Name = "Somalia", Continent = "Africa", Region = "Eastern Africa", Population = 10097000},
                new Country { Code = "SPM", Name = "Saint Pierre and Miquelon", Continent = "North America", Region = "North America", Population = 7000},
                new Country { Code = "STP", Name = "Sao Tome and Principe", Continent = "Africa", Region = "Central Africa", Population = 147000},
                new Country { Code = "SUR", Name = "Suriname", Continent = "South America", Region = "South America", Population = 417000},
                new Country { Code = "SVK", Name = "Slovakia", Continent = "Europe", Region = "Eastern Europe", Population = 5398700},
                new Country { Code = "SVN", Name = "Slovenia", Continent = "Europe", Region = "Southern Europe", Population = 1987800},
                new Country { Code = "SWE", Name = "Sweden", Continent = "Europe", Region = "Nordic Countries", Population = 8861400},
                new Country { Code = "SWZ", Name = "Swaziland", Continent = "Africa", Region = "Southern Africa", Population = 1008000},
                new Country { Code = "SYC", Name = "Seychelles", Continent = "Africa", Region = "Eastern Africa", Population = 77000},
                new Country { Code = "SYR", Name = "Syria", Continent = "Asia", Region = "Middle East", Population = 16125000},
                new Country { Code = "TCA", Name = "Turks and Caicos Islands", Continent = "North America", Region = "Caribbean", Population = 17000},
                new Country { Code = "TCD", Name = "Chad", Continent = "Africa", Region = "Central Africa", Population = 7651000},
                new Country { Code = "TGO", Name = "Togo", Continent = "Africa", Region = "Western Africa", Population = 4629000},
                new Country { Code = "THA", Name = "Thailand", Continent = "Asia", Region = "Southeast Asia", Population = 61399000},
                new Country { Code = "TJK", Name = "Tajikistan", Continent = "Asia", Region = "Southern and Central Asia", Population = 6188000},
                new Country { Code = "TKL", Name = "Tokelau", Continent = "Oceania", Region = "Polynesia", Population = 2000},
                new Country { Code = "TKM", Name = "Turkmenistan", Continent = "Asia", Region = "Southern and Central Asia", Population = 4459000},
                new Country { Code = "TMP", Name = "East Timor", Continent = "Asia", Region = "Southeast Asia", Population = 885000},
                new Country { Code = "TON", Name = "Tonga", Continent = "Oceania", Region = "Polynesia", Population = 99000},
                new Country { Code = "TTO", Name = "Trinidad and Tobago", Continent = "North America", Region = "Caribbean", Population = 1295000},
                new Country { Code = "TUN", Name = "Tunisia", Continent = "Africa", Region = "Northern Africa", Population = 9586000},
                new Country { Code = "TUR", Name = "Turkey", Continent = "Asia", Region = "Middle East", Population = 66591000},
                new Country { Code = "TUV", Name = "Tuvalu", Continent = "Oceania", Region = "Polynesia", Population = 12000},
                new Country { Code = "TWN", Name = "Taiwan", Continent = "Asia", Region = "Eastern Asia", Population = 22256000},
                new Country { Code = "TZA", Name = "Tanzania", Continent = "Africa", Region = "Eastern Africa", Population = 33517000},
                new Country { Code = "UGA", Name = "Uganda", Continent = "Africa", Region = "Eastern Africa", Population = 21778000},
                new Country { Code = "UKR", Name = "Ukraine", Continent = "Europe", Region = "Eastern Europe", Population = 50456000},
                new Country { Code = "UMI", Name = "United States Minor Outlying Islands", Continent = "Oceania", Region = "Micronesia/Caribbean", Population = 0},
                new Country { Code = "URY", Name = "Uruguay", Continent = "South America", Region = "South America", Population = 3337000},
                new Country { Code = "USA", Name = "United States", Continent = "North America", Region = "North America", Population = 278357000},
                new Country { Code = "UZB", Name = "Uzbekistan", Continent = "Asia", Region = "Southern and Central Asia", Population = 24318000},
                new Country { Code = "VAT", Name = "Holy See (Vatican City State)", Continent = "Europe", Region = "Southern Europe", Population = 1000},
                new Country { Code = "VCT", Name = "Saint Vincent and the Grenadines", Continent = "North America", Region = "Caribbean", Population = 114000},
                new Country { Code = "VEN", Name = "Venezuela", Continent = "South America", Region = "South America", Population = 24170000},
                new Country { Code = "VGB", Name = "Virgin Islands, British", Continent = "North America", Region = "Caribbean", Population = 21000},
                new Country { Code = "VIR", Name = "Virgin Islands, U.S.", Continent = "North America", Region = "Caribbean", Population = 93000},
                new Country { Code = "VNM", Name = "Vietnam", Continent = "Asia", Region = "Southeast Asia", Population = 79832000},
                new Country { Code = "VUT", Name = "Vanuatu", Continent = "Oceania", Region = "Melanesia", Population = 190000},
                new Country { Code = "WLF", Name = "Wallis and Futuna", Continent = "Oceania", Region = "Polynesia", Population = 15000},
                new Country { Code = "WSM", Name = "Samoa", Continent = "Oceania", Region = "Polynesia", Population = 180000},
                new Country { Code = "YEM", Name = "Yemen", Continent = "Asia", Region = "Middle East", Population = 18112000},
                new Country { Code = "YUG", Name = "Yugoslavia", Continent = "Europe", Region = "Southern Europe", Population = 10640000},
                new Country { Code = "ZAF", Name = "South Africa", Continent = "Africa", Region = "Southern Africa", Population = 40377000},
                new Country { Code = "ZMB", Name = "Zambia", Continent = "Africa", Region = "Eastern Africa", Population = 9169000},
                new Country { Code = "ZWE", Name = "Zimbabwe", Continent = "Africa", Region = "Eastern Africa", Population = 11669000}
            };

            db.Countries.AddRange(countries);

            db.SaveChanges();
        }
    }
}

