name: .NET Framework Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install Dependencies
      run: dotnet restore
      
    - name: Build and Publish
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./dotnetframework-webapp -r win-x64 --self-contained true /p:UseAppHost=true

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Upload Deployment Package
      uses: actions/upload-artifact@v2
      with:
            name: dotnetframework-webapp
            path: ./dotnetframework-webapp

  standard_version:
    runs-on: ubuntu-latest
    needs: build_and_publish

    steps:
      - uses: actions/checkout@v2
      - name: Bot Configuration
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Standard Version Bump
        uses: qzb/standard-version-action@v1.0.5

      - name: Push Tags
        run: |
          git push --follow-tags origin main

  upload_package_to_ftp:
    runs-on: ubuntu-latest
    needs: build_and_publish

    steps:
      - name: Download Packaged Artifact 1
        uses: actions/download-artifact@v2
        with:
          name: dotnetframework-webapp

      - name: Zip Package
        uses: TheDoctor0/zip-release@0.6.1
        with:
          filename: dotnetframework-webapp.zip
          path: .

      - name: Copy Zip Package
        run: |
          mkdir deploymentTemp
          cp dotnetframework-webapp.zip deploymentTemp
          cd deploymentTemp
          ls

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_ADDRESS }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}    
          local-dir: ./deploymentTemp/
          server-dir: /site/deployments/previewsandbox/
